import type { Metadata } from 'next' // typescript type for metdata
import { Geist, Geist_Mono } from 'next/font/google' // literally just a gooogle font import? but why

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  // loading the font objects in directly to the code (we can attatch these as CSS vairable into HTML tags) | preloaded and optimized rather than <Linking them it>
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  // new way to defined the head of the HTML tag (e.t.c an SPA app that is using react)
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  // top level component of the APP || childeren prop is the content of whatever page we are on cool beans I assume we wrap every component with this then but who knows eh
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
