import type { Metadata } from 'next' // typescript type for metdata
import '../globals.css'

export const metadata: Metadata = {
  // new way to defined the head of the HTML tag (e.t.c an SPA app that is using react)
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  // top level component of the APP || childeren prop is the content of whatever page we are on cool beans I assume we wrap every component with this then but who knows eh
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
